<a href="https://colab.research.google.com/github/YANGZIYI-2025/Homework/blob/main/WIA1007Tutorial03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#1.  Create a numpy array of size 2 x 2
arr_2x2 = np.random.rand(2, 2)
arr_2x2

array([[0.70407396, 0.09096953],
       [0.85316671, 0.66380799]])

In [ ]:
import numpy as np
#2.  Create a random numpy array of size 3 x 4
arr_3x4 = np.random.rand(3, 4)
arr_3x4

array([[0.61529297, 0.01980828, 0.07986597, 0.75586584],
       [0.53178807, 0.50772505, 0.70213008, 0.15911809],
       [0.18362024, 0.50566445, 0.22495664, 0.96017164]])

In [ ]:
import numpy as np
#3.  Create a numpy array of ones and a numpy array of zeroes
arr_ones = np.ones((2, 3))    #ones
arr_zeros = np.zeros((3, 2))     #zeros
arr_ones, arr_zeros

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.]]))

In [ ]:
import numpy as np
#4.  Create a random numpy array of size 6x3 and transpose it
arr_6x3 = np.random.rand(6, 3)
arr_transposed = arr_6x3.T       #transpose
arr_transposed

array([[0.93338304, 0.1775334 , 0.48410487, 0.56802389, 0.68347975,
        0.20220559],
       [0.59087789, 0.82900329, 0.49998733, 0.20737331, 0.90316166,
        0.35200539],
       [0.11979379, 0.12342872, 0.39326047, 0.18301347, 0.67001709,
        0.88189717]])

In [ ]:
import numpy as np
#5.  Create two random numpy array of size n x p and p x m and then compute the dot product
n, p, m = 2, 4, 2
A = np.random.rand(n, p)
B = np.random.rand(p, m)
dot_product = np.dot(A, B)
dot_product

array([[1.77630453, 1.95393649],
       [1.49023515, 1.69789255]])